# Generated by Django 5.2.6 on 2026-01-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0002_botcredentials_loginattempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botcredentials',
            name='admin',
        ),
    ]
