# Generated by Django 5.2.6 on 2026-01-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0003_remove_botcredentials_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
