# Generated by Django 5.2.6 on 2026-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0004_user_is_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hang_protect',
            field=models.IntegerField(default=0),
        ),
    ]
