# Generated by Django 5.2.6 on 2026-01-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0005_user_hang_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptrials',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='uz', max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='uz', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='uz', max_length=2),
        ),
    ]
