# Generated by Django 5.2.6 on 2026-02-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0006_grouptrials_lang_alter_game_lang_alter_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hero_level',
            field=models.IntegerField(default=1),
        ),
    ]
