# Generated by Django 5.2.6 on 2026-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0007_user_hero_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('turnir', 'Turnir')], default='classic', max_length=50),
        ),
    ]
