# Generated by Django 5.2.6 on 2026-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0008_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish'), ('qz', 'Kazakh')], default='uz', max_length=2),
        ),
        migrations.AlterField(
            model_name='grouptrials',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish'), ('qz', 'Kazakh')], default='uz', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish'), ('qz', 'Kazakh')], default='uz', max_length=2),
        ),
    ]
