# Generated by Django 5.2.6 on 2026-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0009_alter_game_lang_alter_grouptrials_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geroy_protection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_geroy_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hang_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
