# Generated by Django 5.2.6 on 2026-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0010_user_geroy_protection_user_is_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_doc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_geroy_protected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hang_protected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_protected',
            field=models.BooleanField(default=True),
        ),
    ]
