# Generated by Django 5.2.6 on 2026-02-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0011_alter_user_is_doc_alter_user_is_geroy_protected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_role_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_geroy_use',
            field=models.BooleanField(default=False),
        ),
    ]
