# Generated by Django 5.2.6 on 2026-02-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_bot', '0012_user_is_active_role_use_user_is_geroy_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active_role_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_geroy_use',
            field=models.BooleanField(default=True),
        ),
    ]
